Unit tests for parser
arturdzm/open-liberty pull request #86
Opened 2018-03-02 16:02 UTC by a-saf

2018-03-02 16:04 UTC, a-saf commented
This PR is for issue #2009

2018-03-14 14:56 UTC, leochr requested changes
Tests look fine. It may be good to consolidate all the methods into the OpenAPIParserTest class, because each test class is parsing the same airlines_openapi.yaml. The method names can be renamed (if needed) to clearly express which item(s) is being tested. Thanks.

2018-03-14 14:56 UTC, leochr commented on dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/impl/parser/test/APIResponsesParserTest.java
> +    @Before
This method will be run before each test method, which doesn't seem to be needed. Perhaps this should be BeforeClass?

2018-03-16 21:06 UTC, leochr approved these changes

2018-03-16 21:06 UTC, merged